name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./JubiAPI/Dockerfile
          push: true
          tags: vonnduven/jubibotapi:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop jubibotapi || true
            docker rm jubibotapi || true
            docker pull vonnduven/jubibotapi:${{ github.sha }}
            docker run -d --restart unless-stopped --name jubibotapi \
              -v /etc/letsencrypt/live/jubibot.com:/app/certs:ro \
              -p 80:8080 -p 443:8081 \
              -e ASPNETCORE_HTTPS_PORTS="8081" \
              -e ASPNETCORE_HTTP_PORTS="8080" \
              -e ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/certs/privkey.pem \
              -e ASPNETCORE_Kestrel__Certificates__Default__KeyType=File \
              -e ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/cert.pem \
              -e DISCORD_TOKEN="${{ secrets.DISCORDTOKEN }}" \
              -e OPENAI_KEY="${{ secrets.OPENAIKEY }}" \
              ${{ secrets.DOCKER_USERNAME }}/jubibotapi:${{ github.sha }}
            sleep 5
            curl -X POST http://localhost/api/Bot/start
            curl http://localhost/api/Bot/status